### ISSUE TITLE
TS90010 error: Type 'Observable<foo>' is not assignable to type 'Observable<foo>'. Two different types with this name exists, but they are unrelated.

### ISSUE THREAD

**Issue by dmattsson** [tomastrajan/ngx-model#1]
Hi

First of all, thanks for an excellent write up of Angular Model Pattern. I love it! 

I just switched to using the npm module instead of just having a single file in my code, and now I'm getting this typescript error (followed the tutorial to the point). Anyone know's whats up?

```
private userModel: Model<Person>;
  public user$: Observable<Person>;


  constructor(private modelFactory: ModelFactory<Person>) {
    this.userModel = modelFactory.create(
      {
        id: null,
        createdAt: null,
        firstName: null,
        fullName: null,
        lastName: null,
        updatedAt: null
      }
    );
    this.user$ = this.userModel.data$;
  }
```

![image](https://user-images.githubusercontent.com/8665566/29526245-7177b39a-8695-11e7-96ce-f79fc5377e60.png)

**Comment by tomastrajan** [comment]
Hi ! It must be somehow two different versions of RXJS in use. Library uses `"rxjs": "^5.4.2"` What are you using ? Maybe we can make RxJS a peer dependency instead any ideas ?

**Comment by dmattsson** [comment]
Hi. Thanks for the prompt reply. I think this had to do with me upgrading typescript to the latest version - apparently there are stricter type checks there. See e.g. https://github.com/Microsoft/TypeScript/issues/16786

Not sure how to fix this long term, but for me it worked to make sure my package.json had the same versions of everything as the latest angular-cli (including typescript 2.3.x).

PS - not sure which RXJS I used, but I think it was 5.4.x at least

Cheers

**Comment by tomastrajan** [comment]
So does it now work for you ? Without need to change ngx-model's version of RxJS ?

**Comment by dmattsson** [comment]
Yes it works when downgrading typescript to 2.3.4. I suspect that it'll reappear the moment angular switches to version 2.4+ though.

Feel free to close the ticket if you think it's better to look at it when/if it becomes a problems in later angular versions. 

Cheers

**Comment by tomastrajan** [comment]
Hey! Rxjs was moved to peerDependencies and version `2.0.0` was release can you please try it with that newer typescript in your project?
