### ISSUE TITLE
Build fails when using angular-cli 1.5.0

### ISSUE THREAD

**Issue by ubenzer** [tomastrajan/ngx-model#3]
If I upgrade my `angular-cli` version from `1.4.3` to `1.5.0` during `ng serve` I get the following error:
```js
ERROR in ./node_modules/ngx-model/index.ts
Module build failed: Error: /Users/ub/Playground/mobility/consumer/web/manager/node_modules/ngx-model/index.ts is not part of the compilation output. Please check the other error messages for details.
    at AngularCompilerPlugin.getCompiledFile (/Users/ub/Playground/mobility/consumer/web/manager/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:629:23)
    at plugin.done.then (/Users/ub/Playground/mobility/consumer/web/manager/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 @ ./src/app/core/core.module.ts 17:0-43
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts
```

Looks like the comment [over here](https://github.com/angular/angular-cli/issues/8284#issuecomment-341417325) is related. It reads

> You have TS files in your node_modules. This really goes against how libraries should be packaged: libraries should never ship their source .ts files.

> The reason for this rule is that the TypeScript version your app isn't necessarily the same as the TS version your library uses. Different versions of TS can produce different output, and give different errors for the same input. They don't even support the same language features. So packaging libraries with TS sources will always break someone's project.

**In case anyone else is affected, a temporary workaround is to modify `tsconfig.app.json`:**

```
  "include": [
    "../src/**/*",
    "../node_modules/ngx-model/**/*.ts"
  ],
  "exclude": [
    "../node_modules/ngx-model/**/*.test.ts"
  ]
```

_A similar change is needed to be done to `tsconfig.spec.json`_

**Comment by tomastrajan** [comment]
Currently in process of releasing version 5.0.0 which will use [ng-packagr](https://github.com/dherges/ng-packagr) to deliver UMD, FESM5 and FESM15 bundles instead of original typescript sources.

**Comment by tomastrajan** [comment]
Ok, version [5.0.0](https://github.com/tomastrajan/ngx-model/blob/master/CHANGELOG.md) is now available on [npm](https://www.npmjs.com/package/ngx-model). Please let me know if that helped 😉.

**Comment by ubenzer** [comment]
Wow, that was quick. It works seamlessly. 🖖 Thanks for the help.

**Comment by tomastrajan** [comment]
Great! Yeah luckily I checked GitHub & could spare some time just now 😉
