### ISSUE TITLE
npm package contains files with last-modified-date 0

### ISSUE THREAD

**Issue by josketres** [tomastrajan/ngx-model#7]
This may not be a big deal for most users of the module, but in our case it is producing errors because for some reason our web-server does not want to serve the files because the last-modified date is 0 (1 Jan 1970) which makes no sense, I'd expect it to be the day when the npm release was created.

Can you please take a look at this?

```
~/my-project (master) $ ls -lh node_modules/ngx-model
total 888
-rw-r--r--  1 my-user  1100429709   1.0K Jan  1  1970 LICENSE
-rw-r--r--  1 my-user  1100429709   6.5K Jan  1  1970 README.md
drwxr-xr-x  6 jmy-user  1100429709   192B Apr 17 08:55 bundles
-rw-r--r--  1 my-user  1100429709    72B Jan  1  1970 index.d.ts
drwxr-xr-x  3 my-user  1100429709    96B Apr 17 08:55 lib
-rw-r--r--  1 my-user  1100429709    77B Jan  1  1970 ngx-model.d.ts
-rw-r--r--  1 my-user  1100429709    82K Jan  1  1970 ngx-model.es5.js
-rw-r--r--  1 my-user  1100429709   127K Jan  1  1970 ngx-model.es5.js.map
-rw-r--r--  1 my-user  1100429709    79K Jan  1  1970 ngx-model.js
-rw-r--r--  1 my-user  1100429709   121K Jan  1  1970 ngx-model.js.map
-rw-r--r--  1 my-user  1100429709   1.4K Jan  1  1970 ngx-model.metadata.json
-rw-r--r--  1 my-user  1100429709   1.7K Jan  1  1970 package.json
```

**Comment by tomastrajan** [comment]
Yes I will have a look, the way release works is that it uses `ngx-packagr` library so maybe it is possible to tweak it there. 

I am using rather convoluted setup of Win 10 with Cygwin on Macbook using Bootcamp so I can imagine the system may go bit weird with that kind of stack 😂
